// HTTP Status Codes Constants
export const HTTP_STATUS = {
  // Success
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,

  // Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,

  // Server Errors
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

// Application Error Codes
export const ERROR_CODES = {
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  USER_NOT_EXIST: 'USER_NOT_EXIST',
  USER_NOT_FOUND_TENANT: 'USER_NOT_FOUND_TENANT',
  NETWORK_ERROR: 'NETWORK_ERROR',
  GENERIC_ERROR: 'GENERIC_ERROR',
  GOOGLE_SIGNIN_FAILED: 'GOOGLE_SIGNIN_FAILED',
  SWITCH_TENANT_FAILED: 'SWITCH_TENANT_FAILED',
};

export default {
  HTTP_STATUS,
  ERROR_CODES,
};
