// Centralized scope/permission constants
export const SCOPES = {
  TENANT_ADMIN: 'TENANT:ADMIN',
  TENANT_SUPER_ADMIN: 'TENANT:SUPER_ADMIN',
  REPORTS_READ: 'reports:READ',
  REPORTS_WRITE: 'reports:WRITE',
  GUEST_EXPLORE: 'guest:explore',
  ADMIN_ACCESS: 'admin:access',

  // Master data module category scopes (match feature_short_name:scope in DB)
  MASTER_DATA_READ:    'MASTER_DATA:READ',
  MASTER_DATA_WRITE:   'MASTER_DATA:WRITE',
  ORGANIZATION_READ:   'ORGANIZATION:READ',
  ORGANIZATION_WRITE:  'ORGANIZATION:WRITE',
  TRANSACTIONS_READ:   'TRANSACTIONS:READ',
  TRANSACTIONS_WRITE:  'TRANSACTIONS:WRITE',
  INVENTORY_READ:      'INVENTORY:READ',
  INVENTORY_WRITE:     'INVENTORY:WRITE',
  CONTACTS_READ:       'CONTACTS:READ',
  CONTACTS_WRITE:      'CONTACTS:WRITE',
  PAYMENTS_READ:       'PAYMENTS:READ',
  PAYMENTS_WRITE:      'PAYMENTS:WRITE',

  // POS (Front Desk) scopes
  POS_CONFIG_READ:    'POS_CONFIG:READ',
  POS_CONFIG_WRITE:   'POS_CONFIG:WRITE',
  POS_ORDER_READ:     'POS_ORDER:READ',
  POS_ORDER_WRITE:    'POS_ORDER:WRITE',
  POS_KITCHEN_READ:   'POS_KITCHEN:READ',
  POS_KITCHEN_WRITE:  'POS_KITCHEN:WRITE',
  POS_BILLING_READ:   'POS_BILLING:READ',
  POS_BILLING_WRITE:  'POS_BILLING:WRITE',
  POS_CRM_READ:       'POS_CRM:READ',
  POS_CRM_WRITE:      'POS_CRM:WRITE',
  POS_OPS_READ:       'POS_OPS:READ',
  POS_OPS_WRITE:      'POS_OPS:WRITE',
  POS_REPORTS_READ:   'POS_REPORTS:READ',
}

export default SCOPES
