// Centralized scope/permission constants
export const SCOPES = {
  TENANT_ADMIN: 'TENANT:ADMIN',
  TENANT_SUPER_ADMIN: 'TENANT:SUPER_ADMIN',
  REPORTS_READ: 'reports:READ',
  REPORTS_WRITE: 'reports:WRITE',
  GUEST_EXPLORE: 'guest:explore',
  ADMIN_ACCESS: 'admin:access',

  // Master data module category scopes (match feature_short_name:scope in DB)
  MASTER_DATA_READ:    'MASTER_DATA:READ',
  MASTER_DATA_WRITE:   'MASTER_DATA:WRITE',
  ORGANIZATION_READ:   'ORGANIZATION:READ',
  ORGANIZATION_WRITE:  'ORGANIZATION:WRITE',
  TRANSACTIONS_READ:   'TRANSACTIONS:READ',
  TRANSACTIONS_WRITE:  'TRANSACTIONS:WRITE',
  INVENTORY_READ:      'INVENTORY:READ',
  INVENTORY_WRITE:     'INVENTORY:WRITE',
  CONTACTS_READ:       'CONTACTS:READ',
  CONTACTS_WRITE:      'CONTACTS:WRITE',
  PAYMENTS_READ:       'PAYMENTS:READ',
  PAYMENTS_WRITE:      'PAYMENTS:WRITE',
}

export default SCOPES
