// Module configuration - defines all CRUD modules in one place
// This enables scalable, consistent management of all data modules

export const MODULE_CATEGORIES = {
  ORGANIZATION: 'Organization',
  CONTACTS: 'Contacts & Addresses',
  MASTER_DATA: 'Master Data',
  INVENTORY: 'Inventory',
  TRANSACTIONS: 'Transactions',
  PAYMENTS: 'Payments',
}

// Module definitions with all metadata
export const MODULES = {
  // ============== MASTER DATA ==============
  taxTypes: {
    key: 'taxTypes',
    name: 'Tax Types',
    endpoint: '/api/taxtypes',
    icon: '💰',
    category: MODULE_CATEGORIES.MASTER_DATA,
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      {
        name: 'Value',
        type: 'number',
        required: true,
        min: 0,
        max: 100,
        step: 0.01,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Value',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  uom: {
    key: 'uom',
    name: 'Units of Measure',
    endpoint: '/api/uom',
    icon: '📏',
    category: MODULE_CATEGORIES.MASTER_DATA,
    displayField: 'UnitName',
    fields: [
      {
        name: 'UnitName',
        label: 'Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      {
        name: 'IsPrimary',
        label: 'Is Primary',
        type: 'boolean',
        default: false,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'UnitName',
      'IsPrimary',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['UnitName'],
  },

  uomFactors: {
    key: 'uomFactors',
    name: 'UOM Factors',
    endpoint: '/api/uomfactors',
    icon: '🔄',
    category: MODULE_CATEGORIES.MASTER_DATA,
    fields: [
      {
        name: 'PrimaryUOMId',
        label: 'Primary UOM',
        type: 'select',
        required: true,
        reference: 'uom',
      },
      {
        name: 'SecondaryUOMId',
        label: 'Secondary UOM',
        type: 'select',
        required: true,
        reference: 'uom',
      },
      {
        name: 'Factor',
        type: 'number',
        required: true,
        min: 0,
        step: 0.000001,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'PrimaryUOMId',
      'SecondaryUOMId',
      'Factor',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: [],
  },

  categories: {
    key: 'categories',
    name: 'Categories',
    endpoint: '/api/categories',
    icon: '📁',
    category: MODULE_CATEGORIES.MASTER_DATA,
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  taxGroups: {
    key: 'taxGroups',
    name: 'Tax Groups',
    endpoint: '/api/taxgroups',
    icon: '📊',
    category: MODULE_CATEGORIES.MASTER_DATA,
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  taxGroupTaxTypeMappers: {
    key: 'taxGroupTaxTypeMappers',
    name: 'Tax Group Mappers',
    endpoint: '/api/taxgrouptaxtypemappers',
    icon: '🔗',
    category: MODULE_CATEGORIES.MASTER_DATA,
    fields: [
      {
        name: 'TaxGroupId',
        label: 'Tax Group',
        type: 'select',
        required: true,
        reference: 'taxGroups',
      },
      {
        name: 'TaxTypeId',
        label: 'Tax Type',
        type: 'select',
        required: true,
        reference: 'taxTypes',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'TaxGroupId',
      'TaxTypeId',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: [],
  },

  // ============== ORGANIZATION ==============
  organizations: {
    key: 'organizations',
    name: 'Organizations',
    endpoint: '/api/organizations',
    icon: '🏛️',
    category: MODULE_CATEGORIES.ORGANIZATION,
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 200 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  branchDetails: {
    key: 'branchDetails',
    name: 'Branch Details',
    endpoint: '/api/branchdetails',
    icon: '🏢',
    category: MODULE_CATEGORIES.ORGANIZATION,
    displayField: 'BranchName',
    fields: [
      {
        name: 'BranchName',
        label: 'Branch Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      {
        name: 'AddressDetailId',
        label: 'Address',
        type: 'select',
        required: true,
        reference: 'addressDetails',
      },
      {
        name: 'ContactDetailId',
        label: 'Contact',
        type: 'select',
        required: true,
        reference: 'contactDetails',
      },
      {
        name: 'OrganizationDetailId',
        label: 'Organization',
        type: 'select',
        required: true,
        reference: 'organizations',
      },
      {
        name: 'TransactionTypeConfigId',
        label: 'Transaction Type Config',
        type: 'select',
        required: true,
        reference: 'transactionTypeConfigs',
      },
      { name: 'TINNo', label: 'TIN No', type: 'text', maxLength: 50 },
      { name: 'GSTIN', label: 'GSTIN', type: 'text', maxLength: 50 },
      { name: 'PAN', label: 'PAN', type: 'text', maxLength: 50 },
      { name: 'CF1', label: 'CF1', type: 'text', maxLength: 50 },
      { name: 'CF2', label: 'CF2', type: 'text', maxLength: 50 },
      { name: 'CF3', label: 'CF3', type: 'text', maxLength: 50 },
      { name: 'CF4', label: 'CF4', type: 'text', maxLength: 50 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'BranchName',
      'AddressDetailId',
      'ContactDetailId',
      'OrganizationDetailId',
      'TransactionTypeConfigId',
      'TINNo',
      'GSTIN',
      'PAN',
      'CF1',
      'CF2',
      'CF3',
      'CF4',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['BranchName'],
  },

  branchUserGroupMappers: {
    key: 'branchUserGroupMappers',
    name: 'Branch User Groups',
    endpoint: '/api/branchusergroupmappers',
    icon: '👥',
    category: MODULE_CATEGORIES.ORGANIZATION,
    fields: [
      {
        name: 'BranchDetailId',
        label: 'Branch',
        type: 'select',
        required: true,
        reference: 'branchDetails',
      },
      {
        name: 'UserGroupId',
        label: 'User Group',
        type: 'text',
        required: true,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'BranchDetailId',
      'UserGroupId',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: [],
  },

  // ============== ACCOUNTING ==============
  // accountTypes: {
  //   key: 'accountTypes',
  //   name: 'Account Types',
  //   endpoint: '/api/accounttypes',
  //   icon: '📒',
  //   category: MODULE_CATEGORIES.MASTER_DATA,
  //   fields: [
  //     { name: 'Name', type: 'text', required: true, maxLength: 100 },
  //     { name: 'Active', type: 'boolean', default: true },
  //   ],
  //   tableColumns: [
  //     'Name',
  //     'Active',
  //     'CreatedBy',
  //     'UpdatedBy',
  //     'CreatedOn',
  //     'UpdatedOn',
  //   ],
  //   searchFields: ['Name'],
  // },

  accountTypeBases: {
    key: 'accountTypeBases',
    name: 'Account Type Bases',
    endpoint: '/api/accounttypebases',
    icon: '📚',
    category: MODULE_CATEGORIES.MASTER_DATA,
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  // ============== TRANSACTIONS ==============
  transactionTypes: {
    key: 'transactionTypes',
    name: 'Transaction Types',
    endpoint: '/api/transactiontypes',
    icon: '📋',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      {
        name: 'TransactionTypeConfigId',
        label: 'Transaction Type Config Tag',
        type: 'select',
        required: true,
        reference: 'transactionTypeConfigs',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'TransactionTypeConfigId',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  transactionTypeConfigs: {
    key: 'transactionTypeConfigs',
    name: 'Transaction Configs',
    endpoint: '/api/transactiontypeconfigs',
    icon: '⚙️',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    displayField: 'TagName',
    fields: [
      {
        name: 'StartCounterNo',
        label: 'Start Counter',
        type: 'number',
        required: true,
        min: 0,
      },
      {
        name: 'TagName',
        label: 'Tag Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      { name: 'Prefix', type: 'text', maxLength: 50 },
      { name: 'Format', type: 'text', required: true, maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Prefix',
      'TagName',
      'Format',
      'StartCounterNo',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Prefix', 'Format'],
  },

  transactionTypeStatuses: {
    key: 'transactionTypeStatuses',
    name: 'Transaction Statuses',
    endpoint: '/api/transactiontypestatuses',
    icon: '🚦',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  transactionTypeBaseConversions: {
    key: 'transactionTypeBaseConversions',
    name: 'Base Conversions',
    endpoint: '/api/transactiontypebaseconversions',
    icon: '🔀',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    // API returns lowercase 'tag' field
    displayField: 'tag',
    fields: [
      {
        name: 'TransactionTypeConfigId',
        label: 'Transaction type Config tag',
        type: 'select',
        required: true,
        reference: 'transactionTypeConfigs',
      },
      {
        name: 'FromTransactionTypeStatusId',
        label: 'From Status',
        type: 'select',
        required: true,
        reference: 'transactionTypeStatuses',
      },
      {
        name: 'ToTransactionTypeStatusId',
        label: 'To Status',
        type: 'select',
        required: true,
        reference: 'transactionTypeStatuses',
      },
      { name: 'Tag', type: 'text', maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    // Prefer expanded/joined fields when available from API (expand=true)
    tableColumns: [
      'Tag',
      'TransactionTypeConfigPrefix',
      'TransactionTypeConfigFormat',
      'FromStatusName',
      'ToStatusName',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Tag', 'FromStatusName', 'ToStatusName'],
  },

  transactionTypeConversionMappers: {
    key: 'transactionTypeConversionMappers',
    name: 'Conversion Mappers',
    // Backend uses singular endpoint: /api/transactiontypeconversionmapper
    endpoint: '/api/transactiontypeconversionmappers',
    icon: '🗺️',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    // Align fields with backend contract: TransactionTypeBaseCoversionId, TransactionDetailLogId, TransactionTypeStatusId
    fields: [
      {
        name: 'TransactionTypeBaseCoversionId',
        label: 'Base Conversion Tag',
        type: 'select',
        required: true,
        reference: 'transactionTypeBaseConversions',
      },
      {
        name: 'TransactionDetailLogId',
        label: 'Transaction Log',
        type: 'select',
        required: true,
        reference: 'transactionDetailLogs',
      },
      {
        name: 'TransactionTypeStatusId',
        label: 'Status',
        type: 'select',
        required: true,
        reference: 'transactionTypeStatuses',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    // Display expanded fields when API returns joined data
    tableColumns: [
      // show the Tag from the referenced base conversion module
      {
        key: 'TransactionTypeBaseCoversionId',
        label: 'Base Conversion Tag',
        reference: 'transactionTypeBaseConversions',
      },
      // 'TransactionTypeConfigId',
      'TransactionNo',
      'TransactionDate',
      'TransactionTypeStatusName',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['TransactionNo', 'TransactionTypeStatusName', 'Tag'],
  },

  transactionDetailLogs: {
    key: 'transactionDetailLogs',
    name: 'Transaction Logs',
    endpoint: '/api/transactiondetaillogs',
    icon: '📝',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    displayField: 'TransactionNo',
    fields: [
      {
        name: 'TransactionNo',
        label: 'Transaction No',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      {
        name: 'TransactionTypeConfigId',
        label: 'Transaction Config Tag',
        type: 'select',
        required: true,
        reference: 'transactionTypeConfigs',
      },
      {
        name: 'TransactionTypeStatusId',
        label: 'Status',
        type: 'select',
        required: true,
        reference: 'transactionTypeStatuses',
      },
      {
        name: 'BranchId',
        label: 'Branch',
        type: 'select',
        required: true,
        reference: 'branchDetails',
      },
      { name: 'TransactionDate', label: 'Date', type: 'date' },
      { name: 'Remarks', type: 'textarea', maxLength: 1000 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'TransactionNo',
      'TransactionTypeConfigId',
      'TransactionDate',
      'TransactionTypeStatusId',
      'BranchId',
      'Remarks',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['TransactionNo', 'Remarks'],
  },

  transactionItemDetails: {
    key: 'transactionItemDetails',
    name: 'Transaction Item Details',
    endpoint: '/api/transactionitemdetails',
    icon: '📦',
    category: MODULE_CATEGORIES.TRANSACTIONS,
    // Align fields with backend contract: TransactionDetailLogId, ItemId, Comment, Active
    fields: [
      {
        name: 'TransactionDetailLogId',
        label: 'Transaction Log',
        type: 'select',
        required: true,
        reference: 'transactionDetailLogs',
      },
      {
        name: 'ItemId',
        label: 'Item',
        type: 'select',
        required: true,
        reference: 'itemDetails',
      },
      { name: 'Comment', type: 'textarea', maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    // Include expanded columns returned by the API when expand=true
    tableColumns: [
      'TransactionNo',
      'TransactionDate',
      'ItemName',
      'ItemCode',
      'ItemSKU',
      'Comment',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['TransactionNo', 'ItemName', 'ItemCode', 'ItemSKU'],
  },

  // ============== INVENTORY ==============
  batchDetails: {
    key: 'batchDetails',
    name: 'Batch Details',
    endpoint: '/api/batchdetails',
    icon: '📦',
    category: MODULE_CATEGORIES.INVENTORY,
    displayField: 'BatchNo',
    fields: [
      {
        name: 'BatchNo',
        label: 'Batch No',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      { name: 'Barcode', label: 'Barcode', type: 'text', maxLength: 100 },
      {
        name: 'MfgDate',
        label: 'Manufactured Date',
        type: 'date',
        required: true,
      },
      { name: 'Expdate', label: 'Expiry Date', type: 'date', required: true },
      {
        name: 'PurchaseDate',
        label: 'Purchase Date',
        type: 'date',
        required: true,
      },
      {
        name: 'IsNonReturnable',
        label: 'Non Returnable',
        type: 'boolean',
        default: false,
      },
      {
        name: 'CostInfoId',
        label: 'Cost Info',
        type: 'select',
        required: true,
        reference: 'costInfos',
      },
      {
        name: 'UOMId',
        label: 'UOM',
        type: 'select',
        required: true,
        reference: 'uom',
      },
      {
        name: 'MapProviderLocationMapperId',
        label: 'Location Detail',
        type: 'select',
        required: true,
        reference: 'mapProviderLocationMappers',
      },
      {
        name: 'BranchDetailId',
        label: 'Branch Name',
        type: 'select',
        required: true,
        reference: 'branchDetails',
      },
      {
        name: 'Quantity',
        label: 'Quantity',
        type: 'number',
        required: true,
        step: 0.0001,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'BatchNo',
      'Barcode',
      'MfgDate',
      'Expdate',
      'PurchaseDate',
      'CostInfoId',
      'UOMId',
      'MapProviderLocationMapperId',
      'BranchDetailId',
      'Quantity',
      'IsNonReturnable',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['BatchNo', 'Barcode'],
  },

  itemDetails: {
    key: 'itemDetails',
    name: 'Item Details',
    endpoint: '/api/itemdetails',
    icon: '🏷️',
    category: MODULE_CATEGORIES.INVENTORY,
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 255 },
      { name: 'Code', type: 'text', maxLength: 50 },
      { name: 'Description', type: 'textarea', maxLength: 1000 },
      {
        name: 'CategoryId',
        label: 'Category',
        type: 'select',
        required: true,
        reference: 'categories',
      },
      {
        name: 'UOMId',
        label: 'UOM',
        type: 'select',
        required: true,
        reference: 'uom',
      },
      {
        name: 'CostInfoId',
        label: 'Cost Info',
        type: 'select',
        required: true,
        reference: 'costInfos',
        // Adds a "Set up" launcher next to the select → guided Cost Info drawer.
        drawer: 'costInfo',
      },
      { name: 'SKU', type: 'text', maxLength: 100 },
      { name: 'Barcode', type: 'text', maxLength: 100 },
      { name: 'HSNCode', label: 'HSN Code', type: 'text', maxLength: 50 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Code',
      'Description',
      'SKU',
      'Barcode',
      'HSNCode',
      'CategoryId',
      'UOMId',
      'CostInfoId',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name', 'Code', 'SKU', 'Barcode'],
  },

  costInfos: {
    key: 'costInfos',
    name: 'Cost Info',
    endpoint: '/api/costinfos',
    icon: '💵',
    category: MODULE_CATEGORIES.INVENTORY,
    displayField: 'Amount',
    fields: [
      { name: 'Amount', type: 'number', required: true, step: 0.0001 },
      {
        name: 'TaxGroupId',
        label: 'Tax Group',
        type: 'select',
        reference: 'taxGroups',
      },
      {
        name: 'IsTaxIncluded',
        label: 'Tax Included',
        type: 'boolean',
        default: false,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Amount',
      'TaxGroupId',
      'IsTaxIncluded',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: [],
  },

  // ============== POS MASTERS (reference-only; nav lives under Front Desk) ==============
  // No `category` → excluded from the Master Data sidebar, but still available to
  // crudService.getReferenceData + FormModal label resolution for the Menu form.
  posChannel: {
    key: 'posChannel',
    name: 'Channels',
    endpoint: '/api/pos/channels',
    icon: '📡',
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Code', type: 'text', required: true, maxLength: 50 },
      { name: 'Description', type: 'textarea', maxLength: 255 },
      { name: 'SortOrder', label: 'Sort Order', type: 'number', default: 0 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: ['Name', 'Code', 'Description', 'SortOrder', 'Active', 'CreatedBy', 'CreatedOn'],
    searchFields: ['Name', 'Code'],
  },

  posVariant: {
    key: 'posVariant',
    name: 'Variants',
    endpoint: '/api/pos/variants',
    icon: '🧩',
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Code', type: 'text', required: true, maxLength: 50 },
      { name: 'Description', type: 'textarea', maxLength: 255 },
      { name: 'SortOrder', label: 'Sort Order', type: 'number', default: 0 },
      { name: 'Price', type: 'number', step: 0.0001 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: ['Name', 'Code', 'Description', 'SortOrder', 'Price', 'Active', 'CreatedBy', 'CreatedOn'],
    searchFields: ['Name', 'Code'],
  },

  posFoodType: {
    key: 'posFoodType',
    name: 'Food Types',
    endpoint: '/api/pos/food-types',
    icon: '🥗',
    displayField: 'Name',
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Code', type: 'text', required: true, maxLength: 50 },
      { name: 'Description', type: 'textarea', maxLength: 255 },
      { name: 'SortOrder', label: 'Sort Order', type: 'number', default: 0 },
      { name: 'IsVeg', label: 'Is Vegetarian', type: 'boolean', default: false },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: ['Name', 'Code', 'Description', 'SortOrder', 'IsVeg', 'Active', 'CreatedBy', 'CreatedOn'],
    searchFields: ['Name', 'Code'],
  },

  // ============== CONTACTS & ADDRESSES ==============
  contactAddressTypes: {
    key: 'contactAddressTypes',
    name: 'Address Types',
    endpoint: '/api/contactaddresstypes',
    icon: '🏠',
    category: MODULE_CATEGORIES.CONTACTS,
    fields: [
      { name: 'Name', type: 'text', required: true, maxLength: 100 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Name',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Name'],
  },

  contactDetails: {
    key: 'contactDetails',
    name: 'Contact Details',
    endpoint: '/api/contactdetails',
    icon: '📞',
    category: MODULE_CATEGORIES.CONTACTS,
    fields: [
      {
        name: 'FirstName',
        label: 'First Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      { name: 'LastName', label: 'Last Name', type: 'text', required: true, maxLength: 100 },
      { name: 'MobileNo', label: 'Mobile No', type: 'text', maxLength: 20 },
      { name: 'AltMobileNo', label: 'Alt Mobile', type: 'text', maxLength: 20 },
      { name: 'Landline1', label: 'Landline 1', type: 'text', maxLength: 20 },
      { name: 'LandLine2', label: 'Landline 2', type: 'text', maxLength: 20 },
      { name: 'Ext1', label: 'Ext 1', type: 'text', maxLength: 10 },
      { name: 'Ext2', label: 'Ext 2', type: 'text', maxLength: 10 },
      {
        name: 'ContactAddressTypeId',
        label: 'Address Type',
        type: 'select',
        required: true,
        reference: 'contactAddressTypes',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'FirstName',
      'LastName',
      'MobileNo',
      { key: 'ContactAddressTypeName', label: 'Address Type' },
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['FirstName', 'LastName', 'MobileNo'],
  },

  addressDetails: {
    key: 'addressDetails',
    name: 'Address Details',
    endpoint: '/api/addressdetails',
    displayField: 'TagName',
    icon: '📍',
    category: MODULE_CATEGORIES.CONTACTS,
    fields: [
      {
        name: 'AddressLine1',
        label: 'Address Line 1',
        type: 'text',
        required: true,
        maxLength: 50,
      },
      {
        name: 'AddressLine2',
        label: 'Address Line 2',
        type: 'text',
        maxLength: 50,
      },
      { name: 'City', type: 'text', maxLength: 50 },
      { name: 'State', type: 'text', maxLength: 50 },
      { name: 'Pincode', type: 'text', maxLength: 50 },
      { name: 'Landmark', type: 'text', maxLength: 50 },
      {
        name: 'ContactAddressTypeId',
        label: 'Address Type',
        type: 'select',
        required: true,
        reference: 'contactAddressTypes',
      },
      {
        name: 'MapProviderLocationMapperId',
        label: 'Location mapper',
        type: 'select',
        reference: 'mapProviderLocationMappers',
      },
      {
        name: 'TagName',
        label: 'Tag Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'AddressLine1',
      'ContactAddressTypeId',
      'TagName',
      'City',
      'State',
      'Pincode',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['AddressLine1', 'City', 'State', 'Pincode'],
  },

  locationDetails: {
    key: 'locationDetails',
    name: 'Location Details',
    endpoint: '/api/locationdetails',
    icon: '🗺️',
    category: MODULE_CATEGORIES.CONTACTS,
    fields: [
      {
        name: 'Lat',
        label: 'Latitude',
        type: 'number',
        required: true,
        step: 0.00000001,
      },
      {
        name: 'Lng',
        label: 'Longitude',
        type: 'number',
        required: true,
        step: 0.00000001,
      },
      { name: 'CF1', label: 'Custom Field 1', type: 'text', maxLength: 255 },
      { name: 'CF2', label: 'Custom Field 2', type: 'text', maxLength: 255 },
      { name: 'CF3', label: 'Custom Field 3', type: 'text', maxLength: 255 },
      { name: 'CF4', label: 'Custom Field 4', type: 'text', maxLength: 255 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Lat',
      'Lng',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: [],
  },

  mapProviders: {
    key: 'mapProviders',
    name: 'Map Providers',
    endpoint: '/api/mapproviders',
    icon: '🌍',
    category: MODULE_CATEGORIES.CONTACTS,
    fields: [
      {
        name: 'ProviderName',
        label: 'Provider Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'ProviderName',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['ProviderName'],
  },

  mapProviderLocationMappers: {
    key: 'mapProviderLocationMappers',
    name: 'Location Mappers',
    endpoint: '/api/mapproviderlocationmappers',
    icon: '📌',
    category: MODULE_CATEGORIES.CONTACTS,
    // Use TagName as display field in UI
    displayField: 'DisplayLabel',
    fields: [
      {
        name: 'MapProviderId',
        label: 'Map Provider',
        type: 'select',
        required: true,
        reference: 'mapProviders',
      },
      {
        name: 'LocationDetailId',
        label: 'Location (Latitude -Longitude)',
        type: 'select',
        required: true,
        reference: 'locationDetails',
      },
      {
        name: 'TagName',
        label: 'Tag Name',
        type: 'text',
        required: true,
        maxLength: 100,
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'MapProviderId',
      'LocationDetailId',
      'TagName',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: [],
  },

  // ============== PAYMENTS ==============
  paymentReceivedTypes: {
    key: 'paymentReceivedTypes',
    name: 'Payment Received Types',
    endpoint: '/api/paymentreceivedtypes',
    icon: '💳',
    category: MODULE_CATEGORIES.PAYMENTS,
    displayField: 'Type',
    fields: [
      {
        name: 'Type',
        label: 'Type',
        type: 'text',
        required: true,
        maxLength: 50,
        placeholder: 'e.g. Full Payment, Partial Payment, Advance, Refund',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Type',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Type'],
  },

  paymentModes: {
    key: 'paymentModes',
    name: 'Payment Modes',
    endpoint: '/api/paymentmodes',
    icon: '💸',
    category: MODULE_CATEGORIES.PAYMENTS,
    displayField: 'Type',
    fields: [
      {
        name: 'Type',
        label: 'Type',
        type: 'text',
        required: true,
        maxLength: 50,
        placeholder: 'e.g. Cash, Card, UPI, Bank Transfer, Cheque',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    tableColumns: [
      'Type',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Type'],
  },

  paymentModeTransactionDetails: {
    key: 'paymentModeTransactionDetails',
    name: 'Payment Transactions',
    endpoint: '/api/paymentmodetransactiondetails',
    icon: '🧾',
    category: MODULE_CATEGORIES.PAYMENTS,
    displayField: 'RefNo',
    fields: [
      {
        name: 'PaymentModeId',
        label: 'Payment Mode',
        type: 'select',
        required: true,
        reference: 'paymentModes',
      },
      { name: 'RefNo', label: 'Ref No', type: 'text', maxLength: 50 },
      { name: 'Comment', type: 'textarea', maxLength: 100 },
      { name: 'CF1', label: 'CF1', type: 'text', maxLength: 50 },
      { name: 'CF2', label: 'CF2', type: 'text', maxLength: 50 },
      { name: 'CF3', label: 'CF3', type: 'text', maxLength: 50 },
      { name: 'CF4', label: 'CF4', type: 'text', maxLength: 50 },
      { name: 'Active', type: 'boolean', default: true },
    ],
    // expand=true adds PaymentModeType from the joined paymentMode record
    tableColumns: [
      { key: 'PaymentModeType', label: 'Payment Mode' },
      'RefNo',
      'Comment',
      'CF1',
      'CF2',
      'CF3',
      'CF4',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['RefNo', 'Comment'],
  },

  paymentDetails: {
    key: 'paymentDetails',
    name: 'Payment Details',
    endpoint: '/api/paymentdetails',
    icon: '💰',
    category: MODULE_CATEGORIES.PAYMENTS,
    displayField: 'TotalAmount',
    fields: [
      {
        name: 'AccountTypeBaseId',
        label: 'Account Type Base',
        type: 'select',
        required: true,
        reference: 'accountTypeBases',
      },
      {
        name: 'TransactionDetailLogId',
        label: 'Transaction Log',
        type: 'select',
        required: true,
        reference: 'transactionDetailLogs',
      },
      {
        name: 'GrossAmount',
        label: 'Gross Amount',
        type: 'text',
        required: true,
        maxLength: 50,
      },
      {
        name: 'TaxesAmount',
        label: 'Taxes Amount',
        type: 'text',
        maxLength: 50,
      },
      {
        name: 'DiscountAmount',
        label: 'Discount Amount',
        type: 'text',
        maxLength: 100,
      },
      {
        name: 'RoundOff',
        label: 'Round Off',
        type: 'text',
        maxLength: 50,
      },
      {
        name: 'TotalAmount',
        label: 'Total Amount',
        type: 'text',
        required: true,
        maxLength: 50,
      },
      {
        name: 'UserId',
        label: 'User ID',
        type: 'text',
        placeholder: 'Logged-in user UUID (CreatedBy)',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    // expand=true adds AccountTypeName, TransactionNo, TransactionDate
    tableColumns: [
      { key: 'AccountTypeName', label: 'Account Type' },
      { key: 'TransactionNo', label: 'Transaction No' },
      { key: 'TransactionDate', label: 'Transaction Date' },
      'GrossAmount',
      'TaxesAmount',
      'DiscountAmount',
      'TotalAmount',
      'RoundOff',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['GrossAmount', 'TotalAmount'],
  },

  paymentBreakups: {
    key: 'paymentBreakups',
    name: 'Payment Breakups',
    endpoint: '/api/paymentbreakups',
    icon: '📊',
    category: MODULE_CATEGORIES.PAYMENTS,
    fields: [
      {
        name: 'AccountTypeBaseId',
        label: 'Account Type Base',
        type: 'select',
        required: true,
        reference: 'accountTypeBases',
      },
      {
        name: 'PaymentDetailId',
        label: 'Payment Detail',
        type: 'select',
        required: true,
        reference: 'paymentDetails',
      },
      {
        name: 'PaymentModeTransactionDetailId',
        label: 'Payment Mode Transaction',
        type: 'select',
        required: true,
        reference: 'paymentModeTransactionDetails',
      },
      {
        name: 'PaymentReceivedTypeId',
        label: 'Payment Received Type',
        type: 'select',
        required: true,
        reference: 'paymentReceivedTypes',
      },
      {
        name: 'Timestamp',
        label: 'Timestamp',
        type: 'datetime',
        required: true,
      },
      {
        name: 'UserId',
        label: 'User ID',
        type: 'text',
        placeholder: 'Logged-in user UUID (CreatedBy)',
      },
      { name: 'Active', type: 'boolean', default: true },
    ],
    // expand=true adds AccountTypeName, TotalAmount, GrossAmount, PaymentModeRefNo, PaymentReceivedTypeName
    tableColumns: [
      { key: 'AccountTypeName', label: 'Account Type' },
      {
        key: 'PaymentDetailId',
        label: 'Payment Detail',
        reference: 'paymentDetails',
      },
      { key: 'PaymentModeRefNo', label: 'Payment Mode Ref' },
      { key: 'PaymentReceivedTypeName', label: 'Received Type' },
      { key: 'TotalAmount', label: 'Total Amount' },
      { key: 'GrossAmount', label: 'Gross Amount' },
      'Timestamp',
      'UserId',
      'Active',
      'CreatedBy',
      'UpdatedBy',
      'CreatedOn',
      'UpdatedOn',
    ],
    searchFields: ['Timestamp'],
  },
}

// Get modules by category
export const getModulesByCategory = () => {
  const grouped = {}
  Object.values(MODULES).forEach((module) => {
    if (!grouped[module.category]) {
      grouped[module.category] = []
    }
    grouped[module.category].push(module)
  })
  return grouped
}

// Get module by key
export const getModule = (key) => MODULES[key]

// Get all module keys
export const getModuleKeys = () => Object.keys(MODULES)

export default MODULES
